/**
 * scripts/template-manifest.ts — the single source of truth for what is
 * "generic" in this forest, i.e. what gets projected into the copier template
 * repo by scripts/sync-template.ts.
 *
 * Three buckets:
 *   - `include`   globs (matched against `git ls-files`, so only *tracked*
 *                 files are ever mirrored) copied into the template verbatim.
 *   - `exclude`   globs subtracted from `include` — generated/local/meta files
 *                 that happen to sit under an included directory.
 *   - `templated` files copied with personal values rewritten to copier
 *                 placeholders and a `.jinja` suffix, so copier renders them.
 *
 * Everything the sync writes is recorded in the template repo's
 * `.sync-manifest.json`; anything previously written but no longer emitted is
 * pruned. Files the template repo owns by hand (copier.yml, the scaffold stubs,
 * its own README/.gitignore) are never in that set, so they are never touched.
 */

/** A file mirrored with substitutions applied and a `.jinja` suffix for copier. */
export interface TemplatedFile {
  /** Path in this repo, relative to the repo root. */
  readonly src: string;
  /** Path in the template repo (usually `<src>.jinja`). */
  readonly dest: string;
  /** Literal `[from, to]` substitutions, applied in order. */
  readonly replace: ReadonlyArray<readonly [string, string]>;
}

export interface TemplateManifest {
  readonly include: readonly string[];
  readonly exclude: readonly string[];
  readonly templated: readonly TemplatedFile[];
}

// copier's Jinja delimiters are retuned to `[[ ]]` / `[% %]` (see copier.yml) so
// they never clash with the `{ }` that saturate Forester and JSON. The templated
// substitutions below therefore emit `[[ … ]]`, not the default `{{ … }}`.
export const TEMPLATE_MANIFEST: TemplateManifest = {
  include: [
    // --- build pipeline (the whole TS/Python toolchain) ---
    "scripts/**",
    "server.ts",
    "highlight/**",

    // --- theme (vendored base theme + local customisations) ---
    "theme/**",

    // --- tooling / editor / lint / TS config ---
    "tsconfig.json",
    "eslint.config.mjs",
    "Justfile",
    ".forester-formatter.json",
    ".forester-links.json",
    ".vscode/**",
    ".editorconfig",

    // --- CI + git hooks (kept faithful to the current deploy model:
    //     pre-push builds locally, CI uploads the committed output/notes) ---
    ".github/**",
    ".githooks/**",
    ".husky/**",

    // --- framework trees (macros/preamble every note imports) ---
    "trees/base-macros.tree",
    "trees/erct-macros.tree",
    "trees/erct-latex-preamble.tree",

    // --- brand assets + language reference ---
    "notes-icon.svg",
    "FORESTER_LANGUAGE_SPEC.md",

    // --- vendored graph-view artifact, committed so scaffolded forests build in
    //     CI without fetching it (see scripts/build/stages/graph-vendor.ts) ---
    "vendor/graph-view/**",
  ],

  exclude: [
    // The sync machinery is source-repo-only; a scaffolded forest never runs it.
    "scripts/sync-template.ts",
    "scripts/template-manifest.ts",
    // husky's generated wrapper dir — regenerated by the `prepare` script.
    ".husky/_/**",
    // theme's local dev sandbox install (not tracked, but guard anyway).
    "theme/dev/node_modules/**",
    "theme/dev/.tmp/**",
  ],

  templated: [
    {
      // Generic apart from the published URL, which becomes a copier prompt.
      src: "forest.toml",
      dest: "forest.toml.jinja",
      replace: [['"https://kaierikniermann.github.io/notes/"', '"[[ site_url ]]"']],
    },
    {
      // Scripts + deps are fully generic; only name/author are personal.
      src: "package.json",
      dest: "package.json.jinja",
      replace: [
        ['"name": "forester"', '"name": "[[ project_slug ]]"'],
        ['"author": ""', '"author": "[[ author ]]"'],
      ],
    },
    {
      // Copied verbatim (no `.jinja`, so copier does not render it) — routed
      // through `templated` because it reads straight from disk, which also
      // works when the lockfile is untracked and thus invisible to git ls-files.
      src: "pnpm-lock.yaml",
      dest: "pnpm-lock.yaml",
      replace: [],
    },
  ],
};
